<?php

/**
 *  Implements a hook_install().
 */

 function interior_custom_email_install($is_syncing){
     if ($is_syncing){
         return;
     }
 

    $config = \Drupal::configFactory()->getEditable('systme.mail');
    $mail_plugins = $config->get('interface');
    if(in_array('interior_custom_email', array_keys($mail_plugins))) {
        return;
    }

    $mail_plugins['interior_custom_email'] = 'interior_custom_email';
    $config->set('interface', $mail_plugins)->save();
}